[package]
name = "increment-5"
version = "0.1.0"
edition = "2024"

[dependencies]
# see the root cargo.toml [workspace.dependencies]
bevy = { workspace = true }
bevy_render = { workspace = true }
leafwing-input-manager = { workspace = true }

